#!/usr/bin/env bash

set -eu -o pipefail
shopt -s nullglob globstar

if [ -d "./electrum_nmc" ]; then
    echo "Rebranding needed"
    exit 1
fi

for i in **/*.py; do
    if ./contrib/print_python_strings "$i" "nmc" \
        | grep -v 'Electrum-NMC by the Namecoin developers'; then
        echo "Rebranding needed"
        exit 1
    fi

    if ./contrib/print_python_strings "$i" "namecoin" \
        | grep -v 'electrum/tests/test_util\.py.*notnamecoin:' \
        | grep -v 'Electrum-NMC by the Namecoin developers'; then
        echo "Rebranding needed"
        exit 1
    fi

    if ./contrib/print_python_strings "$i" "sat" \
        | grep -v "amount_msat" \
        | grep -v "amount_sat" \
        | grep -v "balance_msat" \
        | grep -v "capacity_sat" \
        | grep -v "channel_reserve_satoshis" \
        | grep -v "dust_limit_sat" \
        | grep -v "fee_msat" \
        | grep -v "fee_sat" \
        | grep -v "fee_base_msat" \
        | grep -v "funding_sat" \
        | grep -v "htlc_minimum_msat" \
        | grep -v "htlc_maximum_msat" \
        | grep -v "local_msat" \
        | grep -v "max_htlc_value_in_flight_msat" \
        | grep -v "MAXIMUM_HTLC_MINIMUM_MSAT_ACCEPTED" \
        | grep -v "push_msat" \
        | grep -v "remote_msat" \
        | grep -v "total_msat" \
        | grep -v "value_sats" \
        | grep -v "satisfied" \
        | grep -v "electrum/gui/text.py.*'satoshis'" \
        | grep -v "electrum/old_mnemonic.py" \
        | grep -v "electrum/util.py.*'Satoshis(%d)'" \
        | grep -v "electrum/util.py.*'Satoshis({self.value})'" \
        | grep -v "electrum/tests/.*\.py"; then
        echo "Rebranding needed"
        exit 1
    fi

    # Namecoin Bech32 addresses
    if ./contrib/print_python_strings "$i" "['\"]nc1"; then
        echo "Rebranding needed"
        exit 1
    fi
done

EXCEPTIONS="--exclude=check_chi_rebranding --exclude=RELEASE-NOTES --exclude-dir=.git"

if grep -r $EXCEPTIONS 'electrum_nmc\.icns' ./; then
    echo "Rebranding needed"
    exit 1
fi

if grep -r $EXCEPTIONS 'electrum_nmc\.ico' ./; then
    echo "Rebranding needed"
    exit 1
fi

if grep -r $EXCEPTIONS 'electrum_nmc\.png' ./; then
    echo "Rebranding needed"
    exit 1
fi

exit 0
