#!/bin/bash

set -e

if ! which pyuic5 > /dev/null 2>&1; then
    echo "Please install pyqt5-dev-tools"
    exit 1
fi

for i in dnsdialog dnssubdomaindialog; do
    pyuic5 electrum_chi/electrum/gui/qt/forms/$i.ui --execute --output=electrum_chi/electrum/gui/qt/forms/$i.py
    sed -i s/qvalidatedlineedit/.qvalidatedlineedit/ electrum_chi/electrum/gui/qt/forms/$i.py
done
