#!/bin/bash
version=`python3 -c "import electrum_chi.electrum; print(electrum_chi.electrum.version.ELECTRUM_VERSION)"`
sig=`./run_electrum_chi -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
